import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-auto-generated',
  templateUrl: './auto-generated.component.html',
  styleUrls: ['./auto-generated.component.scss']
})
export class AutoGeneratedComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

  onTap($event) {
    alert({
      title: "И големият въпрос е:",
      message: "Здравко педал ли е?",
      okButtonText: "Голям",
      cancelButtonText: "Да",
    });
  }
}
