import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-auto-generated',
  templateUrl: './auto-generated.component.html',
  styleUrls: ['./auto-generated.component.scss']
})
export class AutoGeneratedComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

  onTap($event) {
    alert({
      // title: "Race selection",
      message: "Zdravko pedal li e?",
      okButtonText: "Da",
      cancelButtonText: "Golqm",
  });
  }
}
